STOPWORDS = {
    "and",
    "about",
    "after",
    "again",
    "against",
    "along",
    "among",
    "around",
    "as",
    "at",
    "by",
    "between",
    "because",
    "before",
    "being",
    "both",
    "could",
    "every",
    "first",
    "from",
    "have",
    "into",
    "other",
    "their",
    "there",
    "these",
    "those",
    "through",
    "under",
    "while",
    "where",
    "which",
    "would",
    "per",
    "study",
    "material",
    "chapter",
    "notes",
    "topic",
    "section",
    "of",
    "off",
    "on",
    "onto",
    "or",
    "over",
    "than",
    "to",
    "using",
    "used",
    "this",
    "that",
    "with",
    "they",
    "them",
    "into",
    "your",
    "when",
    "what",
    "will",
    "each",
    "first",
    "higher",
    "lower",
    "such",
    "then",
    "our",
    "we",
    "also",
    "more",
    "most",
    "very",
}
GENERIC_TERMS = {
    "concept",
    "concepts",
    "example",
    "examples",
    "system",
    "process",
    "processes",
    "information",
    "detail",
    "details",
    "document",
    "documents",
    "section",
    "sections",
    "chapter",
    "chapters",
    "result",
    "results",
    "factor",
    "factors",
}
CONNECTOR_TOKENS = {
    "and",
    "or",
    "of",
    "to",
    "for",
    "in",
    "on",
    "at",
    "by",
    "via",
    "with",
    "from",
    "vs",
    "versus",
}
OUTLINE_HINT_PATTERNS = [
    r"\blearning objectives?\b",
    r"\bchapter outline\b",
    r"\btable of contents\b",
    r"\bcontents?\b",
    r"\boverview\b",
    r"\bagenda\b",
]
FORMULA_HINT_PATTERNS = [
    r"=",
    r"\bvar(?:iance)?\b",
    r"\bcov(?:ariance)?\b",
    r"\bbeta\b",
    r"\bstd(?:\.|andard deviation)?\b",
    r"\bcapm\b",
    r"\be\[[^\]]+\]",
]
BAD_LABEL_PREFIXES = (
    "alternative example",
    "both are",
    "computing ",
    "counting ",
    "data ",
    "figure ",
    "higher ",
    "let s ",
    "lets ",
    "page ",
    "realistic ",
    "rest",
    "risk beta",
    "solution ",
    "table ",
    "then ",
    "textbook example",
    "total ",
    "using ",
    "where ",
)
VISIBLE_SOURCE_LEAK_PATTERNS = [
    r"\bpage\s+\d+\b",
    r"\bsection\s+\d+\b",
    r"\bslide\s+\d+\b",
    r"\bsource\b",
    r"\bchunk\b",
    r"\bfile\b",
    r"\.pdf\b",
    r"\.docx\b",
    r"\.pptx\b",
]
CARD_DEFINITION_MARKERS = (
    " is ",
    " are ",
    " refers to ",
    " means ",
    " describes ",
    " measures ",
    " represents ",
    " captures ",
    " reflects ",
    " equals ",
    " requires ",
    " states ",
    " uses ",
    " depends on ",
    " occurs when ",
    " arises when ",
    " can be used to ",
)
COMMON_VERBS = {
    "allow",
    "allows",
    "absorb",
    "absorbs",
    "affect",
    "affects",
    "calculate",
    "calculates",
    "compare",
    "compares",
    "convert",
    "converts",
    "create",
    "creates",
    "describe",
    "describes",
    "discuss",
    "discusses",
    "estimate",
    "estimates",
    "explain",
    "explains",
    "fix",
    "fixes",
    "happen",
    "happens",
    "increase",
    "increases",
    "influence",
    "influences",
    "maintain",
    "maintains",
    "measure",
    "measures",
    "package",
    "packages",
    "pause",
    "pauses",
    "produce",
    "produces",
    "regulate",
    "regulates",
    "repair",
    "repairs",
    "represent",
    "represents",
    "reproduce",
    "reproduces",
    "shape",
    "shapes",
    "share",
    "shares",
    "state",
    "states",
    "store",
    "stores",
    "transfer",
    "transfers",
    "involve",
    "involves",
    "involving",
    "use",
    "uses",
}
BOUNDARY_WORDS = {
    "in",
    "into",
    "during",
    "through",
    "across",
    "with",
    "from",
    "for",
    "when",
    "where",
    "while",
    "most",
    "more",
    "less",
    "most",
    "only",
    "than",
}
DISPLAY_ACRONYMS = {"ATP", "DNA", "RNA", "NADPH", "CO2", "NPV", "ROI", "IRR", "VAT", "IP"}
PROMPT_START_TOKENS = {
    "assess",
    "assuming",
    "calculate",
    "compute",
    "describe",
    "determine",
    "discuss",
    "estimate",
    "explain",
    "given",
    "how",
    "if",
    "suppose",
    "use",
    "what",
    "when",
    "which",
    "why",
}
NOISE_LINE_PATTERNS = [
    r"\ball rights reserved\b",
    r"\ball right reserved\b",
    r"\bcopyright\b",
    r"\bpearson education\b",
    r"\bpage\s+\d+\b",
    r"\bchapter outline\b",
    r"\blearning objectives?\b",
    r"\bcontents?\b",
    r"\btable of contents\b",
    r"\bspring finals\b",
]
NOISE_TOKENS = {
    "answer",
    "rights",
    "reserved",
    "copyright",
    "pearson",
    "education",
    "equation",
    "objective",
    "objectives",
    "outline",
    "chapter",
    "contents",
    "overview",
    "page",
    "pdf",
    "pptx",
    "question",
    "slide",
    "suppose",
    "txt",
    "textbook",
    "tsv",
    "week",
    "xlsx",
    "csv",
    "docx",
}
DEFINITION_MARKERS = (
    " is ",
    " are ",
    " refers to ",
    " means ",
    " describes ",
    " defines ",
    " uses ",
    " allows ",
    " depends on ",
    " includes ",
    " occurs when ",
    " converts ",
    " creates ",
    " reduces ",
    " increases ",
)
INLINE_NOISE_PATTERNS = [
    r"all rights reserved",
    r"all right reserved",
    r"copyright",
    r"alternative example\s+\d+(?:\.\d+)?(?:\s*\(\d+\s*of\s*\d+\))?",
    r"textbook example\s+\d+(?:\.\d+)?(?:\s*\(\d+\s*of\s*\d+\))?",
    r"equation\s+\(?\d+\s+of\s+\d+\)?",
]
